ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Copy over the Zed_Multi_Cam Folder
COPY ./Zed_Multi_Cam /opt/ros_ws/src/zed-multicam
WORKDIR /opt/ros_ws/
RUN . /opt/ros/noetic/setup.sh && \
    catkin_make

# Install QR detection
WORKDIR / 
# @Leo:
# RUN sudo apt-get install --fix-missing -y ros-noetic-aruco-ros

# Copy over all relevant configuration files
COPY ./single.launch /opt/ros/noetic/share/aruco_ros/launch/single.launch
COPY ./aruco.sh ./aruco.sh
COPY ./common.yaml /opt/ros_ws/src/zed-ros-wrapper/zed_wrapper/params/common.yaml
COPY ./zed.yaml   /opt/ros_ws/src/zed-ros-wrapper/zed_wrapper/params/zed.yaml
COPY ./zedm.yaml   /opt/ros_ws/src/zed-ros-wrapper/zed_wrapper/params/zedm.yaml
COPY ./zed2.yaml   /opt/ros_ws/src/zed-ros-wrapper/zed_wrapper/params/zed2.yaml
COPY ./zed2i.yaml   /opt/ros_ws/src/zed-ros-wrapper/zed_wrapper/params/zed2i.yaml
COPY ./start.sh /start.sh
COPY ./objects_performance_2.2.model /usr/local/zed/resources/objects_performance_2.2.model

# Run the start.sh file to launch 
RUN chmod +x start.sh
CMD ./start.sh
#ENTRYPOINT ["bash", "/start.sh"]
