# params/zed2i.yaml
# Parameters for Stereolabs ZED2 camera
---

general:
    camera_model:               'zed2i'

depth:
    min_depth:                  0.3             # Min: 0.2, Max: 3.0 - Default 0.7 - Note: reducing >
    max_depth:                  5.0             # Max: 40.0

pos_tracking:
    imu_fusion:                 true            # enable/disable IMU fusion. When set to false, only>

sensors:
    sensors_timestamp_sync:     false           # Synchronize Sensors messages timestamp with latest>
    max_pub_rate:               200.            # max frequency of publishing of sensors data. MAX: >
    publish_imu_tf:             true            # publish `IMU -> <cam_name>_left_camera_frame` TF

object_detection:
    od_enabled:                 true           # True to enable Object Detection [not available for>
    model:                      0               # '0': MULTI_CLASS_BOX - '1': MULTI_CLASS_BOX_ACCURA>
    confidence_threshold:       50              # Minimum value of the detection confidence of an ob>
    max_range:                  15.             # Maximum detection range
    object_tracking_enabled:    true            # Enable/disable the tracking of the detected objects
    body_fitting:               true           # Enable/disable body fitting for 'HUMAN_BODY_X' mod>
    mc_people:                  true            # Enable/disable the detection of persons for 'MULTI>
    mc_vehicle:                 true            # Enable/disable the detection of vehicles for 'MULT>
    mc_bag:                     true            # Enable/disable the detection of bags for 'MULTI_CL>
    mc_animal:                  true            # Enable/disable the detection of animals for 'MULTI>
    mc_electronics:             true            # Enable/disable the detection of electronic devices>
    mc_fruit_vegetable:         true            # Enable/disable the detection of fruits and vegetab>
    mc_sport:                   true            # Enable/disable the detection of sport-related obje>

