obstacle_range: 2.0
raytrace_range: 3.5
base_local_planner: dwa_local_planner/DWAPlannerROS

# TODO
# footprint: [[0.40, 0.40], [0.40, -0.40], [-0.40, -0.40], [-0.40, 0.40]]
# footprint: [[0.6475, 0.435], [0.6475, -0.435], [-0.6475, -0.435], [-0.6475, 0.435]]
footprint: [[-0.35, -0.35], [1,-0.35], [1,0.35], [-0.35, 0.35]]
# Correct:
# footprint: [[0.5475, 0.335], [0.5475, -0.335], [-0.5475, -0.335], [-0.5475, 0.335]]
map_topic: /staticmap
subscribe_to_updates: true
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
static_layer:
    map_topic: /map
    subscribe_to_updates: true

plugins:
    - {name: static_layer,           type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::VoxelLayer"}
# obstacle_layer:
#     observation_sources: laser_scan_sensor
#     laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 5.0, obstacle_range: 6.0, raytrace_range: 8.5}

# obstacle_layer:
#     observation_sources: laser_scan_sensor
#     laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}



# obstacle_layer:
#     observation_sources: point_cloud_sensor
#     observation_persistence: 0.0
#     point_cloud_sensor: {
#         min_obstacle_height: 0.5,
#         sensor_frame: camera_link,
#         data_type: PointCloud2,
#         topic: /cloud,
#         marking: true,
#         clearing: true,
#         inf_is_valid: true,
#         clear_on_max_reading: true
#     }


obstacle_layer:
  # ...
  observation_sources: scan
  scan:
    data_type: LaserScan
    sensor_frame: camera_link,
    topic: scan # Your LaserScan topic
    marking: true
    clearing: false
    inf_is_valid: true # This parameter does the trick!
    min_obstacle_height: -3
    max_obstacle_height: 3
