global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 40
  height: 40
  origin_x: -20
  origin_y: -20
  rolling_window: true
  inflation_radius: 1
  resolution: 0.05
  plugins:
  #  - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: mapping_layer,        type: "costmap_2d::StaticLayer"}
