local_costmap:
  global_frame: map
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25
  robot_base_frame: base_link
  # static_map: false
  rolling_window: true
  width: 7
  height: 7
  origin_x: 0.5
  origin_y: 0.5
  resolution: 0.05
  inflation_radius: 0.1
  # plugins:
      # - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
      # - {name: static_layer,        type: "costmap_2d::StaticLayer"}
      # - {name: mapping_layer,        type: "costmap_2d::StaticLayer"}
      # - {name: rgbd_obstacle_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
