TrajectoryPlannerROS:
  max_vel_x: 3
  min_vel_x: 0.4
  max_vel_theta: 0.03
  min_vel_theta: -0.03
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 0.01
  acc_lim_x: 2.5
  acc_lim_Y: 2.5

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.5
  oscillation_reset_dist: 0.1
