wheele:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # # Position Controllers ---------------------------------------
  # joint1_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: back_right_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint2_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: back_left_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'joint_wheel_back_left'
    right_wheel: 'joint_wheel_back_right'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    # wheel_radius : 0.1725
    # wheel_separation : 0.585