# Parameters set with the ARTA wheelchair in mind
TrajectoryPlannerROS:
    # Robot Configuration
    acc_lim_x: 1.0
    acc_lim_y: 0.0
    acc_lim_theta: 1.0

    max_vel_x: 1.0
    min_vel_x: 0.3

    max_vel_theta: 1.0 
    min_vel_theta: -1.0
    min_in_place_vel_theta: 0.3

    escape_vel: -0.4

    # Strafing not possible with ARTA
    holonomic_robot: false

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.2
    xy_goal_tolerance: 0.3
    latch_xy_goal_tolerance: false

    # Forward Simulation Parameters
    sim_time: 1.55                     # More computationally heavy but allows trajectory to pass through narrow passway
    sim_granularity: 0.025             # Step size between points on a trajectory
    angular_sim_granularity: 0.025
    vx_samples: 20
    vtheta_samples: 40

    # Trajectory Scoring Parameters
    meter_scoring: true     # Assume goal and path distances are in metres
    pdist_scale: 1.2        # Weighting for how much it should stick to the global path plan
    gdist_scale: 0.8        # Weighting for how much it should attempt to reach its local goal
    occdist_scale: 0.01     # Weighting for how much the controller should avoid obstacles

    heading_lookahead: 0.325 
    heading_scoring: false  
    heading_scoring_timestep: 1.0

    dwa: true    # Try without due to poor acceleration constraints
    publish_cost_grid_pc: false 

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.25  # How far to travel (metres) before resetting oscillation flags
    escape_reset_dist: 0.1
    escape_reset_theta: 0.1