# Parameters set with the ARTA wheelchair in mind
footprint: [[-0.45, -0.35], [-0.45, 0.35], [0.45, 0.35], [0.45, -0.35]]
footprint_padding: 0.00

robot_base_frame: base_link

transform_tolerance: 1.5  # Tolerable delay in transforms, s
map_type: costmap

# Update map with information about obstacles that are within m distance of the base
obstacle_range: 5
# Attempt to clear out space in front of base
raytrace_range: 5.5
  
obstacle_layer:
    # Sensor management 
    observation_sources:  scan
    scan:
        expected_update_rate: 1
        observation_persistence: 0.0 # How long to keep each sensor reading (in seconds), 0.0 only keeps most recent
        data_type: LaserScan
        topic: base_scan
        marking: true
        clearing: true
        inf_is_valid: true # Converts inf readings from scanner into max range
        max_obstacle_height: 1.0
        min_obstacle_height: -1.0

inflation_layer:
    inflation_radius: 1.55    # Max. distance from an obstacle at which costs are incurred for planning paths
    cost_scaling_factor: 2.57 # Exponential rate at which the obstacle cost drops off (default: 10) - Lower makes robot stay further from obstacles

static_layer:
    map_topic: map
    subscribe_to_updates: true