global_frame: odom

rolling_window: true
track_unknown_space:  false    # True needed for disabling global path planning through unknown space
static_map: false

width: 30.0
height: 30.0
resolution: 0.1

update_frequency: 5.0     # Map update frequency
publish_frequency: 2.0    # Publish frequency

plugins:
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}