GlobalPlanner:              
    old_navfn_behavior: false                     # Do not mirror behaviour of navfn
    use_quadratic: true                           # Use the quadratic approximation of the potential
    use_dijkstra: true                            # Use dijkstra's algorithm, otherwise A* default
    use_grid_path: false                          # Create a path that follows the grid boundaries, otherwise use a gradient descent method

    allow_unknown: true                           # Allow planner to plan through unknown space, default true

    visualize_potential: true                     # Visualise the potential map

    default_tolerance: 0.1

    lethal_cost: 253                              # Will not produce path if too low
    neutral_cost: 66                              # Open space value
    cost_factor: 0.55                             # Translates costs of inputs evenly over output range, needs tweaking for spread 