global_frame: odom

rolling_window: true
static_map: false

width: 10.0
height: 10.0
resolution: 0.02

update_frequency: 10.0     # Map update frequency
publish_frequency: 5.0    # Publish frequency

plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}