recovery_behaviors: 
    - name: 'conservative_reset'
      type: 'clear_costmap_recovery/ClearCostmapRecovery'
    - name: 'aggressive_reset'
      type: 'clear_costmap_recovery/ClearCostmapRecovery'

recovery_behavior_enabled: true
clearing_rotation_allowed: false

# Control loop for sending velocity commands
controller_frequency: 10.0
# Wait time for controller before space-clearing operations, s
controller_patience: 10.0
# Rate in Hz to run the global planning loop, 0.0 means only runs when a new goal is received or path blocked
planner_frequency: 10.0
# Wait time for planner to find a new valid plan before space-clearing operations, s
planner_patience: 5.0

# Oscillation timeout before executing recovery behaviours, s
oscillation_timeout: 0.0
# Distance for robot to not be considered oscillating, m
oscillation_distance: 0.2

# Distance away from robot at which obstacles will be cleared from the costmap, m
conservative_reset_dist: 3.0